const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const CREATED = 201;
const BAD_REQUEST = 400;
const NOT_AUTHORIZED = 401;

module.exports = {
  NOT_FOUND,
  SERVER_ERROR,
  CREATED,
  BAD_REQUEST,
  NOT_AUTHORIZED,
};
